import 'dotenv/config';
import { db } from '../src/db/db';
import { specialist_info } from '../src/db/drizzle/schema';

async function seedSpecialistInfo() {
  const specialists = [
    {
      SpecialistID: 1,
      SpecialistName: 'Dr. Jose A. Urquidez',
      Specialties: 'Physiatry, Emergency Medicine',
      Address: '11851 Jollyville Rd, Suite 103, Austin, TX',
      Expertise: 'Cerebral Palsy, Decorticate Posture, Decerebrate Posture, Opisthotonos',
      Classification: null,
    },
    {
      SpecialistID: 2,
      SpecialistName: 'Dr. Gregory Marchand',
      Specialties: 'Family Medicine',
      Address: '16004 Snowdonia Cv, Bee Cave, TX',
      Expertise: 'Cerebral Palsy, Bronchitis, Anemia, High Cholesterol',
      Classification: null,
    },
    {
      SpecialistID: 3,
      SpecialistName: 'Dr. Maureen R. Nelson',
      Specialties: 'Physiatry',
      Address: '8611 N Mopac Expy Ste 300, Austin, TX',
      Expertise: 'Cerebral Palsy',
      Classification: null,
    },
    {
      SpecialistID: 4,
      SpecialistName: 'Dr. Norman M. Whisenant',
      Specialties: 'Physiatry',
      Address: '1106 W Dittmar Blvd, Austin, TX',
      Expertise: 'Cerebral Palsy, Hemiplegia, Subarachnoid, Hemorrhage, Meige Disease',
      Classification: null,
    },
    {
      SpecialistID: 5,
      SpecialistName: 'Dr. Judy L. Kim',
      Specialties: 'Family Medicine',
      Address: '1101 Camino La Costa, Austin, TX',
      Expertise: 'Moebius Syndrome, Down Syndrome, Cerebral Palsy',
      Classification: null,
    },
    {
      SpecialistID: 6,
      SpecialistName: 'Dr. Maureen R. Nelson',
      Specialties: 'Physiatry',
      Address: '8611 N Mopac Expy Ste 300, Austin, TX',
      Expertise: 'Cerebral Palsy',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 7,
      SpecialistName: 'Dr. Shelia B. Patel',
      Specialties: 'Physiatry',
      Address: '1201 W Louis Henna Blvd, Austin, TX',
      Expertise: 'Rhabdomyolysis, Stroke, Chronic Subdural Hematoma',
      Classification: 'Spastic',
    },
    {
      SpecialistID: 8,
      SpecialistName: 'Dr. Justin C. Chavez',
      Specialties: 'Physiatry, Pain Medicine',
      Address: '351 Seton Pkwy, Round Rock, TX',
      Expertise: 'Necrotizing Myopathy, Stroke, Subdural Hematoma, Tomaculous Neuropathy',
      Classification: 'Spastic',
    },
    {
      SpecialistID: 9,
      SpecialistName: 'Dr. Vettaikorumakankav V. Vedanarayanan',
      Specialties: 'Pediatrics, Neurology',
      Address: '1301 Medical Pkwy, Suite 200, Cedar Park, TX',
      Expertise: 'Inclusion Body Myositis, Amyotonia Congenita, Congenital Myasthenic Syndrome, Limb-Girdle Muscular Dystrophy',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 10,
      SpecialistName: 'Dr. Norman M. Whisenant',
      Specialties: 'Physiatry',
      Address: '1106 W Dittmar Blvd, Austin, TX',
      Expertise: 'Cerebral Palsy, Hemiplegia, Subarachnoid, Hemorrhage, Meige Disease',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 11,
      SpecialistName: 'Dr. Ricardo A. Cruz',
      Specialties: 'Internal Medicine',
      Address: '1201 W 38th St, Austin, TX',
      Expertise: 'Ogilvie Syndrome, Peptic Ulcer, Cellulitis, Endoscopy, and Bone Marrow Aspiration',
      Classification: 'Spastic, Mixed-Typed',
    },
    {
      SpecialistID: 12,
      SpecialistName: 'Dr. Douglas H. Rankin',
      Specialties: 'Family Medicine',
      Address: '6800 W Gate Blvd #132-326, Austin, TX',
      Expertise: 'Familial Chronic Mucocutaneous Candidiasis, Generalized Tonic-Clonic Seizure, Cerebral Palsy',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 13,
      SpecialistName: 'Dr. James H. Shane',
      Specialties: 'Internal Medicine',
      Address: '12221 N Mopac Expy, Austin, TX',
      Expertise: 'Muscle Atrophy, Vascular Dementia, Dysgraphia, Gastronomy, Endoscopy',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 14,
      SpecialistName: 'Dr. Steven A. Inano',
      Specialties: 'Physiatry',
      Address: '919 E 32nd St, Austin, TX',
      Expertise: 'Stroke, Subdural Hematoma, Foot Drop, Chronic Subdural Hematoma',
      Classification: 'Spastic',
    },
    {
      SpecialistID: 15,
      SpecialistName: 'Dr. Talia R. Collier',
      Specialties: 'Physiatry, Pediatrics',
      Address: '8611 N Mopac Expy Ste 300, Austin, TX',
      Expertise: 'Myelomeningocele, Primary Lateral Sclerosis, Cerebral Palsy',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 16,
      SpecialistName: 'Dr. Karen C. Keough',
      Specialties: 'Neurology, Pediatrics',
      Address: '7940 Shoal Creek Blvd, Ste 100, Austin, TX',
      Expertise: 'Autosomal Dominant Nocturnal Frontal Lobe Epilepsy, Seizures, Epilepsy, Lennox-Gastaut Syndrome',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 17,
      SpecialistName: 'Dr. Katherine S. Labiner',
      Specialties: 'Neurology',
      Address: '7940 Shoal Creek Blvd, Ste 100, Austin, TX',
      Expertise: 'Seizures, Status Epilepticus, Epilepsy',
      Classification: null,
    },
    {
      SpecialistID: 18,
      SpecialistName: 'Dr. Michael J. Soileau',
      Specialties: 'Neurology',
      Address: '11279 Taylor Draper Ln, Austin, TX',
      Expertise: 'Parkinson\'s Disease, Progressive Supranuclear Palsy, Progressive Supranuclear Palsy Atypical, Deep Brain Stimulation',
      Classification: 'Dyskinetic',
    },
    {
      SpecialistID: 19,
      SpecialistName: 'Dr. John R. Jefferson',
      Specialties: 'Neurology',
      Address: '1500 Red River St, Austin, TX',
      Expertise: 'Generalized Tonic-Clonic Seizure, Seizures, Foot Drop, Stroke',
      Classification: 'Spastic, Dyskinetic',
    },
    {
      SpecialistID: 20,
      SpecialistName: 'Dr. Jefferson T. Miley',
      Specialties: 'Neurology, Interventional Radiology',
      Address: '1601 Trinity St 704 F, Austin, TX',
      Expertise: 'Stroke, Subarachnoid Hemorrhage, Brain Aneurysm, Transmyocardial Revascularization, Stent Placement',
      Classification: 'Spastic, Dyskinetic',
    },
    {
      SpecialistID: 21,
      SpecialistName: 'Dr. Deborah E. Briggs',
      Specialties: 'Neurology',
      Address: '1600 W 38th St, Austin, TX',
      Expertise: 'Memory Loss, Seizures, Tuberous Sclerosis, Tuberous Sclerosis Complex',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 22,
      SpecialistName: 'Dr. Dave F. Clarke',
      Specialties: 'Neurology, Pediatric Neurology',
      Address: '1301 Barbara Jordan Blvd, Suite 200, Austin, TX',
      Expertise: 'Epilepsy, Seizures, Absence Seizure, Generalized Tonic-Clonic Seizure',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 23,
      SpecialistName: 'Dr. Pradeep N. Modur',
      Specialties: 'Neurology',
      Address: '1600 W 38th St, Austin, TX',
      Expertise: 'Seizures, Generalized Tonic-Clonic Seizure, Epilepsy, Brown-Sequard Syndrome',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 24,
      SpecialistName: 'Dr. Anupama Alareddy',
      Specialties: 'Neurology',
      Address: '1600 W 38th St, Austin, TX',
      Expertise: 'Seizures, Epilepsy, Memory Loss, Generalized Tonic-Clonic Seizure',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 25,
      SpecialistName: 'Dr. Richard A. Sawyers',
      Specialties: 'Neurology',
      Address: '5251 W Hwy 290, Austin, TX',
      Expertise: 'Facioscapulohumeral Muscular Dystrophy, Opsoclonus-Myoclonus Syndrome, Distal Median Nerve Dysfunction, Seizures',
      Classification: null,
    },
    {
      SpecialistID: 26,
      SpecialistName: 'Dr. Steven J. Warach',
      Specialties: 'Neurology',
      Address: '1601 Trinity St, Austin, TX',
      Expertise: 'Stroke, Dysarthria, Increased Intracranial Pressure, Transient Ischemic Attack, Thrombectomy',
      Classification: 'Spastic',
    },
    {
      SpecialistID: 27,
      SpecialistName: 'Dr. Mariana G. Varga',
      Specialties: 'Neurology, Physiatry, Psychiatry',
      Address: '3001 Bee Cave Rd, Suite 210, Austin, TX',
      Expertise: 'Parkinson\'s Disease, Essential Tremor, Serotonin Syndrome, Athetosis',
      Classification: 'Dyskinetic',
    },
    {
      SpecialistID: 28,
      SpecialistName: 'Dr. Andrea S. Raymond',
      Specialties: 'Neurology',
      Address: '2785 E 7th St, Austin, TX',
      Expertise: 'Generalized Tonic-Clonic Seizure, Seizures, Cerebellar Degeneration, Parkinson\'s Disease',
      Classification: 'Ataxic, Dyskinetic, Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 29,
      SpecialistName: 'Dr. Patrick C. Nolan',
      Specialties: 'Neurology',
      Address: '2785 E 7th St, Austin, TX',
      Expertise: 'Serotonin Syndrome, Neuralgia, Wernicke-Korsakoff Syndrome, Parkinson\'s Disease',
      Classification: 'Dyskinetic, Spastic',
    },
    {
      SpecialistID: 30,
      SpecialistName: 'Dr. Poonam M. Manasa',
      Specialties: 'Physiatry',
      Address: '919 E 32nd St, Austin, TX',
      Expertise: 'Necrotizing Myopathy, Familial Periodic Paralysis, Stroke, Subarachnoid Hemorrhage',
      Classification: 'Mixed-Typed, Spastic',
    },
    {
      SpecialistID: 31,
      SpecialistName: 'Dr. Kenny-bao B. Tran',
      Specialties: 'Physiatry, Hospital Medicine',
      Address: '2000 Scenic Dr, Georgetown, TX',
      Expertise: 'Subdural Hematoma, Rhabdomyolysis, Stroke, Chronic Subdural Hematoma, Gastrostomy',
      Classification: 'Mixed-Typed, Spastic',
    },
  ];

  try {
    console.log('Seeding specialist_info table...');
    await db.insert(specialist_info).values(specialists).onConflictDoNothing();
    console.log('Seeding complete!');
  } catch (error) {
    console.error('Seeding error:', error);
  } finally {
    process.exit(0);
  }
}

seedSpecialistInfo(); 